/**
 * `seeya project adopt <session> <projectId>`'s own orchestration (V2-T29, D-045 item 4, D-047
 * item 6). Runs the adoption on a FORK of the chosen session, never the original — `--fork-session`
 * (already used by the deep capture generator since S2-T2) copies the transcript to a new file; the
 * original never receives a line. The fork is resumed interactively, in ITS OWN original directory
 * — a deliberate choice, not an accident (maintainer's own reasoning, 2026-09-24): the Claude Code
 * loads that directory's own `CLAUDE.md`, auto-memory, configuration and skills by working
 * directory, so opening there is what gives the fork all of that; opened in the project instead, it
 * would have only the transcript. The project itself is released via `--add-dir`, and
 * `adapters/harness/adopt-instruction.ts#buildAdoptionInstruction` asks the session to carry over
 * into the project whatever, from what's locally available to it, belongs to this specific work.
 * The person approves every write on the spot, per D-047's own reasoning for choosing interactive
 * resumption over any headless `--permission-mode` (docs/spikes/N-adocao-de-sessao.md's own "a
 * V2-T29 não pode assumir que retomar basta para poder escrever").
 *
 * Same shape `application/project-open.ts#openProject` already established for a command that
 * takes the project lock, blocks for an entire interactive `claude` lifetime, and releases the
 * lock afterward — reused here (`application/project-lock.ts#acquireProjectLock`/
 * `releaseProjectLock`), not reimplemented.
 */
import path from 'node:path';
import type {
  Clock,
  ForkCleanup,
  ForkRegistration,
  HarnessOpenResult,
  ProcessControl,
  ProjectLock,
  SessionAdoptionLauncher,
  Storage,
  WorkspaceRepository,
} from '../core/ports.js';
import type { ProjectLockInfo } from '../core/project-lock.js';
import type { DiscoveredSession, SessionState } from '../core/types.js';
import { classifyState } from '../core/classification.js';
import { findAdoptionRecord } from '../core/adoption-registry.js';
import { isValidProjectId } from '../core/project-id.js';
import { buildProjectCommitMessage } from '../core/project-commit.js';
import { createProject, resolveWorkspaceRoot } from './workspace.js';
import { acquireProjectLock, releaseProjectLock } from './project-lock.js';

export interface AdoptSessionDeps {
  readonly storage: Storage;
  readonly workspace: WorkspaceRepository;
  readonly projectLock: ProjectLock;
  readonly processControl: ProcessControl;
  readonly clock: Clock;
  readonly forkRegistration: ForkRegistration;
  readonly forkCleanup: ForkCleanup;
  readonly adoptionLauncher: SessionAdoptionLauncher;
  readonly seeyaHome: string;
  /** `Config.idleMinutes` — `classifyState`'s own second input, needed to refuse adopting a
   * session that's running right now (`alive`/`idle` both mean "the process is up"). */
  readonly idleMinutes: number;
  /** Same `CLAUDE_CODE_SESSION_ID` source as `application/workspace.ts
   * #WorkspaceCommandDeps.sessionId` — only used for the project-creation commit's own trailer
   * (item 1: adopting into a project that doesn't exist yet creates it first, exactly like `seeya
   * project create`). The adoption commit itself always uses `forkSessionId` below, never this. */
  readonly sessionId: string | undefined;
  /** This `seeya project adopt` invocation's OWN process — it blocks for the fork's entire
   * interactive lifetime, so its liveness IS the lock's liveness, same reasoning
   * `ProjectOpenDeps.pid`/`procStart` already carry. */
  readonly pid: number;
  readonly procStart: string | undefined;
  /** The fork's own id, generated by the composition root BEFORE this runs
   * (`packages/cli/src/composition.ts`, `node:crypto#randomUUID` — randomness stays out of
   * `core/`/`application/`). Passed to `claude --session-id`, written into `.seeya-lock`, and — only
   * once the person confirms the commit — into the `Seeya-Session-Id` trailer and
   * `adoptions.json`'s own `forkSessionId`. */
  readonly forkSessionId: string;
  /** V2-T34 item 1: threaded through only so `ensureProjectExists` below can hand a full
   * `WorkspaceCommandDeps`-shaped object to `createProject` when adopting into a project that
   * doesn't exist yet — same pair `application/workspace.ts#WorkspaceCommandDeps` itself carries. */
  readonly nodePath: string;
  readonly cliEntryPath: string;
}

/** D-025: three answers, never flattened into a boolean — `unavailable` (no interactive terminal
 * to ask through) is not the same fact as an explicit `decline`, exactly the distinction
 * `application/project-open.ts#ReadOnlyOpenAnswer` already draws for a different confirmation. */
export type ConfirmAdoptionAnswer = 'commit' | 'decline' | 'unavailable';

export type ConfirmAdoptionCommit = (
  changedFiles: readonly string[],
) => Promise<ConfirmAdoptionAnswer>;

/** Same three-way shape as `ConfirmAdoptionAnswer` (D-025), for the OTHER confirmation this task
 * needs: before anything is created at all, not after the fork already ran. */
export type ConfirmAdoptionLaunchAnswer = 'proceed' | 'decline' | 'unavailable';

export type ConfirmAdoptionLaunch = (info: {
  readonly originalCwd: string;
  readonly projectDir: string;
  readonly projectId: string;
}) => Promise<ConfirmAdoptionLaunchAnswer>;

export interface AdoptSessionCallbacks {
  /**
   * Asked BEFORE the project is created, the lock is taken, or the fork is registered — same
   * "explain, then wait for an explicit answer" shape `application/project-open.ts
   * #ConfirmReadOnlyOpen` already established for a locked project, now for a different problem
   * (task-23 comment, the second acceptance round): the interactive harness takes over the
   * terminal right after this, so whatever it's told has to be read and understood BEFORE that
   * happens, not printed and immediately scrolled past. `cli/project-command.ts` renders the
   * explanation (where the fork opens and why, where the project lives, and the `project open`
   * follow-up) and asks. `undefined` behaves exactly like `'unavailable'` (D-025: never a silent
   * proceed) — every production caller always supplies one.
   */
  readonly confirmLaunch?: ConfirmAdoptionLaunch;
  /** `undefined` behaves exactly like `'unavailable'` (D-025: never a silent commit) — every
   * production caller (`cli/project-command.ts`) always supplies one. */
  readonly confirmCommit?: ConfirmAdoptionCommit;
}

export type AdoptSessionResult =
  | { readonly kind: 'invalidId'; readonly projectId: string }
  | {
      readonly kind: 'sessionRunning';
      readonly sessionId: string;
      readonly name: string;
      readonly state: SessionState;
    }
  | {
      readonly kind: 'alreadyAdopted';
      readonly sessionId: string;
      readonly projectId: string;
      readonly adoptedAt: Date;
    }
  /** Item 8: the person was shown the explanation and explicitly said no — nothing was created,
   * nothing registered (`forks.json` never even sees this attempt). */
  | { readonly kind: 'launchConfirmationDeclined'; readonly projectId: string }
  /** Item 8: no interactive terminal to ask through — same D-025 refusal
   * `application/project-open.ts#OpenProjectResult`'s own `lockConfirmationUnavailable` already
   * gives a locked `open`, applied here before anything is created at all. */
  | { readonly kind: 'launchConfirmationUnavailable'; readonly projectId: string }
  | { readonly kind: 'projectLocked'; readonly projectId: string; readonly heldBy: ProjectLockInfo }
  | { readonly kind: 'failedToStart'; readonly projectId: string }
  /** Nothing was written inside the project — nothing to show, nothing to confirm. Same cleanup as
   * an explicit decline (the fork is discarded, nothing stays registered), reported distinctly so
   * the person can tell "you said no" apart from "there was nothing to say yes to". */
  | { readonly kind: 'noChanges'; readonly projectId: string; readonly forkSessionId: string }
  | {
      readonly kind: 'declined';
      readonly projectId: string;
      readonly forkSessionId: string;
      readonly changedFiles: readonly string[];
    }
  /** No way to ask (no interactive terminal) — unlike `declined`, nothing is deleted and nothing is
   * committed: the fork stays registered (hidden, as any capture fork would be) and the written
   * files stay on disk, uncommitted, for a later interactive run to resolve (docs/QUESTOES.md
   * Q-091 — the spec is silent on this exact case; deleting real, approved-by-nobody-yet work
   * because a terminal wasn't attached would be worse than leaving it alone). */
  | {
      readonly kind: 'confirmationUnavailable';
      readonly projectId: string;
      readonly forkSessionId: string;
      readonly changedFiles: readonly string[];
    }
  | {
      readonly kind: 'adopted';
      readonly projectId: string;
      readonly forkSessionId: string;
      readonly changedFiles: readonly string[];
    };

/** Item 1's own "sessão aberta agora recusada": `alive`/`idle` both mean the process is running
 * right now — retomar o que está rodando abriria uma segunda cópia, so BOTH are refused, never
 * just `alive` (D-025: `idle` is still a live process, not a claim that nothing is happening). */
function isSessionRunning(state: SessionState): boolean {
  return state === 'alive' || state === 'idle';
}

/** The two refusals that never touch any port at all: a session running right now, or an original
 * already adopted somewhere on this device. `null` means "proceed". Extracted so `adoptSession`
 * itself stays a straight-line sequence (AGENTS.md § "Retorno cedo"). */
async function checkAdoptionPreconditions(
  deps: AdoptSessionDeps,
  original: DiscoveredSession,
  now: Date,
): Promise<AdoptSessionResult | null> {
  const state = classifyState(original, { now, idleMinutes: deps.idleMinutes });
  if (isSessionRunning(state)) {
    return { kind: 'sessionRunning', sessionId: original.sessionId, name: original.name, state };
  }
  const existing = findAdoptionRecord(await deps.storage.readAdoptions(), original.sessionId);
  if (existing === null) {
    return null;
  }
  return {
    kind: 'alreadyAdopted',
    sessionId: original.sessionId,
    projectId: existing.projectId,
    adoptedAt: existing.adoptedAt,
  };
}

/** Item 1: adopting into a project that doesn't exist yet creates it first — reuses `createProject`
 * (`application/workspace.ts`) rather than duplicating its skeleton-write-plus-commit sequence
 * (AGENTS.md: "nada de duplicação"). Its own `invalidId`/`alreadyExists` outcomes are both fine
 * here: `invalidId` is unreachable (the caller already checked), and `alreadyExists` is exactly the
 * "adopt into an existing project" case this function has to support anyway. */
async function ensureProjectExists(deps: AdoptSessionDeps, projectId: string): Promise<void> {
  await createProject(deps, projectId);
}

/** Item 2's own cleanup for both "declined" and "nothing to confirm": deletes the fork's transcript
 * (the D-012 exception, `ForkCleanup.deleteFork`) and drops its `forks.json` entry
 * (`ForkRegistration.unregister`) — "a cópia é apagada e nada fica registrado". */
async function discardFork(deps: AdoptSessionDeps): Promise<void> {
  await deps.forkCleanup.deleteFork(deps.forkSessionId);
  await deps.forkRegistration.unregister(deps.forkSessionId);
}

/** Item 4's own promotion: commits the project's changes with the fork's own identity in the
 * trailer (D-047 item 6: the fork IS the project's session from here on), drops the `forks.json`
 * entry WITHOUT deleting the transcript (unlike `discardFork` — this fork is being kept), and
 * records the adoption so the original can never be adopted again. */
async function commitAdoption(
  deps: AdoptSessionDeps,
  root: string,
  projectId: string,
  originalSessionId: string,
  changedFiles: readonly string[],
  now: Date,
): Promise<AdoptSessionResult> {
  const message = buildProjectCommitMessage(
    `Adopt session ${originalSessionId} into project ${projectId}`,
    projectId,
    deps.forkSessionId,
  );
  await deps.workspace.commitAll(root, projectId, message);
  await deps.forkRegistration.unregister(deps.forkSessionId);
  const adoptions = await deps.storage.readAdoptions();
  await deps.storage.saveAdoptions([
    ...adoptions,
    { originalSessionId, forkSessionId: deps.forkSessionId, projectId, adoptedAt: now },
  ]);
  return { kind: 'adopted', projectId, forkSessionId: deps.forkSessionId, changedFiles };
}

/** Asks `callbacks.confirmLaunch`, or resolves `'unavailable'` when none was given (D-025 — same
 * "never a silent default" `application/project-open.ts#confirmReadOnlyOpen` already applies).
 * Item 8's own gate, asked before anything is created. */
async function confirmAdoptionLaunch(
  callbacks: AdoptSessionCallbacks | undefined,
  originalCwd: string,
  projectDir: string,
  projectId: string,
): Promise<ConfirmAdoptionLaunchAnswer> {
  if (callbacks?.confirmLaunch === undefined) {
    return 'unavailable';
  }
  return callbacks.confirmLaunch({ originalCwd, projectDir, projectId });
}

/** Asks `callbacks.confirmCommit`, or resolves `'unavailable'` when none was given (D-025 — same
 * "never a silent default" `application/project-open.ts#confirmReadOnlyOpen` already applies). */
async function confirmCommit(
  callbacks: AdoptSessionCallbacks | undefined,
  changedFiles: readonly string[],
): Promise<ConfirmAdoptionAnswer> {
  if (callbacks?.confirmCommit === undefined) {
    return 'unavailable';
  }
  return callbacks.confirmCommit(changedFiles);
}

/** What to do once the fork session has closed AND the person (or the absence of one) has
 * answered — the three-way branch item 4's spec describes, kept separate from `finishAdoption` so
 * that function's own lock release stays a single, unmissable line at the end. */
async function decideAdoptionOutcome(
  deps: AdoptSessionDeps,
  root: string,
  projectId: string,
  originalSessionId: string,
  changedFiles: readonly string[],
  callbacks: AdoptSessionCallbacks | undefined,
): Promise<AdoptSessionResult> {
  if (changedFiles.length === 0) {
    await discardFork(deps);
    return { kind: 'noChanges', projectId, forkSessionId: deps.forkSessionId };
  }
  const answer = await confirmCommit(callbacks, changedFiles);
  if (answer === 'commit') {
    return commitAdoption(deps, root, projectId, originalSessionId, changedFiles, deps.clock.now());
  }
  if (answer === 'decline') {
    await discardFork(deps);
    return { kind: 'declined', projectId, forkSessionId: deps.forkSessionId, changedFiles };
  }
  return {
    kind: 'confirmationUnavailable',
    projectId,
    forkSessionId: deps.forkSessionId,
    changedFiles,
  };
}

/** The tail of `adoptSession`, after the fork's interactive harness has already closed: reads what
 * changed inside the project, decides the outcome (item 4), and always releases the lock before
 * returning — mirrors `application/project-open.ts#finishOpen`'s own shape. */
async function finishAdoption(
  deps: AdoptSessionDeps,
  root: string,
  projectId: string,
  originalSessionId: string,
  callbacks: AdoptSessionCallbacks | undefined,
): Promise<AdoptSessionResult> {
  const changedFiles = await deps.workspace.listChangedFiles(root, projectId);
  const result = await decideAdoptionOutcome(
    deps,
    root,
    projectId,
    originalSessionId,
    changedFiles,
    callbacks,
  );
  await releaseProjectLock(deps, root, projectId, deps.pid);
  return result;
}

/** Registers the fork (before spawning — D-012, survives a crash the same way
 * `adapters/generation/fork-registration.ts#registerFork`'s own docstring argues for captures),
 * launches it, and unwinds the registration if it never actually started. Returns the raw
 * `HarnessOpenResult` — `adoptSession` decides what `failedToStart` means for the lock. */
async function launchAdoptionFork(
  deps: AdoptSessionDeps,
  projectDir: string,
  original: DiscoveredSession,
  now: Date,
): Promise<HarnessOpenResult> {
  await deps.forkRegistration.register(deps.forkSessionId, now);
  const launch = await deps.adoptionLauncher.adopt(
    original.cwd,
    projectDir,
    original.sessionId,
    deps.forkSessionId,
  );
  if (launch.kind === 'failedToStart') {
    await deps.forkRegistration.unregister(deps.forkSessionId);
  }
  return launch;
}

/**
 * @example
 * const result = await adoptSession(deps, discoveredSession, 'auth-hardening', {
 *   confirmCommit: (files) => askThePerson(files),
 * });
 */
export async function adoptSession(
  deps: AdoptSessionDeps,
  original: DiscoveredSession,
  projectId: string,
  callbacks?: AdoptSessionCallbacks,
): Promise<AdoptSessionResult> {
  if (!isValidProjectId(projectId)) {
    return { kind: 'invalidId', projectId };
  }

  const now = deps.clock.now();
  const refusal = await checkAdoptionPreconditions(deps, original, now);
  if (refusal !== null) {
    return refusal;
  }

  // Item 8: explained and confirmed BEFORE anything is created — the project doesn't exist yet,
  // no lock is taken, no fork is registered. `resolveWorkspaceRoot` alone is not "creating the
  // copy" (it only resolves/persists WHERE the workspace lives on this device, the same read
  // every other `seeya project` command does freely) — needed here only to compute `projectDir`
  // for the explanation text.
  const root = await resolveWorkspaceRoot(deps.storage, deps.seeyaHome);
  const projectDir = path.join(root, projectId);
  const confirmation = await confirmAdoptionLaunch(callbacks, original.cwd, projectDir, projectId);
  if (confirmation !== 'proceed') {
    return {
      kind:
        confirmation === 'decline' ? 'launchConfirmationDeclined' : 'launchConfirmationUnavailable',
      projectId,
    };
  }

  await ensureProjectExists(deps, projectId);

  const lock = await acquireProjectLock(
    deps,
    root,
    projectId,
    { pid: deps.pid, procStart: deps.procStart, sessionId: deps.forkSessionId },
    now,
  );
  if (lock.decision.kind === 'refuse') {
    return { kind: 'projectLocked', projectId, heldBy: lock.decision.heldBy };
  }

  const launch = await launchAdoptionFork(deps, projectDir, original, now);
  if (launch.kind === 'failedToStart') {
    await releaseProjectLock(deps, root, projectId, deps.pid);
    return { kind: 'failedToStart', projectId };
  }

  return finishAdoption(deps, root, projectId, original.sessionId, callbacks);
}
