/**
 * `application/project-adopt.ts`'s own shared types — pulled into their own module (V2-T72) so
 * `application/project-adopt-outcome.ts` can depend on them WITHOUT importing back from
 * `project-adopt.ts` itself (that would be a dependency cycle: `project-adopt.ts` already imports
 * `finishAdoption` FROM `project-adopt-outcome.ts`). `project-adopt.ts` re-exports every one of
 * these, so nothing about the public `@seeya-ai/engine/application/project-adopt.js` surface
 * changes for any caller (`packages/cli/src/project-command.ts`,
 * `packages/app/src/electron/project-ipc.ts`, every test importing from it today).
 */
import type { ProjectLockInfo } from '../core/project-lock.js';
import type {
  Clock,
  ForkCleanup,
  ForkRegistration,
  ManifestRestoreOutcome,
  ProcessControl,
  ProjectLock,
  SessionAdoptionLauncher,
  Storage,
  WorkspaceRepository,
} from '../core/ports.js';
import type { SessionState } from '../core/types.js';

export interface AdoptSessionDeps {
  readonly storage: Storage;
  readonly workspace: WorkspaceRepository;
  readonly projectLock: ProjectLock;
  readonly processControl: ProcessControl;
  readonly clock: Clock;
  readonly forkRegistration: ForkRegistration;
  readonly forkCleanup: ForkCleanup;
  readonly adoptionLauncher: SessionAdoptionLauncher;
  readonly seeyaHome: string;
  /** `Config.idleMinutes` — `classifyState`'s own second input, needed to refuse adopting a
   * session that's running right now (`alive`/`idle` both mean "the process is up"). */
  readonly idleMinutes: number;
  /** Same `CLAUDE_CODE_SESSION_ID` source as `application/workspace.ts
   * #WorkspaceCommandDeps.sessionId` — only used for the project-creation commit's own trailer
   * (item 1: adopting into a project that doesn't exist yet creates it first, exactly like `seeya
   * project create`). The adoption commit itself always uses `forkSessionId` below, never this. */
  readonly sessionId: string | undefined;
  /** This `seeya project adopt` invocation's OWN process — it blocks for the fork's entire
   * interactive lifetime, so its liveness IS the lock's liveness, same reasoning
   * `ProjectOpenDeps.pid`/`procStart` already carry. */
  readonly pid: number;
  readonly procStart: string | undefined;
  /** The fork's own id, generated by the composition root BEFORE this runs
   * (`packages/cli/src/composition.ts`, `node:crypto#randomUUID` — randomness stays out of
   * `core/`/`application/`). Passed to `claude --session-id`, written into `.seeya-lock`, and — only
   * once the person confirms the commit — into the `Seeya-Session-Id` trailer and
   * `adoptions.json`'s own `forkSessionId`. */
  readonly forkSessionId: string;
  /** V2-T34 item 1: threaded through only so `ensureProjectExists` below can hand a full
   * `WorkspaceCommandDeps`-shaped object to `createProject` when adopting into a project that
   * doesn't exist yet — same pair `application/workspace.ts#WorkspaceCommandDeps` itself carries. */
  readonly nodePath: string;
  readonly cliEntryPath: string;
}

/** D-025: three answers, never flattened into a boolean — `unavailable` (no interactive terminal
 * to ask through) is not the same fact as an explicit `decline`, exactly the distinction
 * `application/project-open.ts#ReadOnlyOpenAnswer` already draws for a different confirmation. */
export type ConfirmAdoptionAnswer = 'commit' | 'decline' | 'unavailable';

export type ConfirmAdoptionCommit = (
  changedFiles: readonly string[],
) => Promise<ConfirmAdoptionAnswer>;

/** Same three-way shape as `ConfirmAdoptionAnswer` (D-025), for the OTHER confirmation this task
 * needs: before anything is created at all, not after the fork already ran. */
export type ConfirmAdoptionLaunchAnswer = 'proceed' | 'decline' | 'unavailable';

export type ConfirmAdoptionLaunch = (info: {
  readonly originalCwd: string;
  readonly projectDir: string;
  readonly projectId: string;
}) => Promise<ConfirmAdoptionLaunchAnswer>;

export interface AdoptSessionCallbacks {
  /**
   * Asked BEFORE the project is created, the lock is taken, or the fork is registered — same
   * "explain, then wait for an explicit answer" shape `application/project-open.ts
   * #ConfirmReadOnlyOpen` already established for a locked project, now for a different problem
   * (task-23 comment, the second acceptance round): the interactive harness takes over the
   * terminal right after this, so whatever it's told has to be read and understood BEFORE that
   * happens, not printed and immediately scrolled past. `cli/project-command.ts` renders the
   * explanation (where the fork opens and why, where the project lives, and the `project open`
   * follow-up) and asks. `undefined` behaves exactly like `'unavailable'` (D-025: never a silent
   * proceed) — every production caller always supplies one.
   */
  readonly confirmLaunch?: ConfirmAdoptionLaunch;
  /** `undefined` behaves exactly like `'unavailable'` (D-025: never a silent commit) — every
   * production caller (`cli/project-command.ts`) always supplies one. */
  readonly confirmCommit?: ConfirmAdoptionCommit;
}

export type AdoptSessionResult =
  | { readonly kind: 'invalidId'; readonly projectId: string }
  | {
      readonly kind: 'sessionRunning';
      readonly sessionId: string;
      readonly name: string;
      readonly state: SessionState;
    }
  | {
      readonly kind: 'alreadyAdopted';
      readonly sessionId: string;
      readonly projectId: string;
      readonly adoptedAt: Date;
    }
  /** Item 8: the person was shown the explanation and explicitly said no — nothing was created,
   * nothing registered (`forks.json` never even sees this attempt). */
  | { readonly kind: 'launchConfirmationDeclined'; readonly projectId: string }
  /** Item 8: no interactive terminal to ask through — same D-025 refusal
   * `application/project-open.ts#OpenProjectResult`'s own `lockConfirmationUnavailable` already
   * gives a locked `open`, applied here before anything is created at all. */
  | { readonly kind: 'launchConfirmationUnavailable'; readonly projectId: string }
  | { readonly kind: 'projectLocked'; readonly projectId: string; readonly heldBy: ProjectLockInfo }
  | { readonly kind: 'failedToStart'; readonly projectId: string }
  /** Nothing was written inside the project — nothing to show, nothing to confirm. Same cleanup as
   * an explicit decline (the fork is discarded, nothing stays registered), reported distinctly so
   * the person can tell "you said no" apart from "there was nothing to say yes to". */
  | {
      readonly kind: 'noChanges';
      readonly projectId: string;
      readonly forkSessionId: string;
      readonly manifestRestore: ManifestRestoreOutcome;
    }
  | {
      readonly kind: 'declined';
      readonly projectId: string;
      readonly forkSessionId: string;
      readonly changedFiles: readonly string[];
      readonly manifestRestore: ManifestRestoreOutcome;
    }
  /** No way to ask (no interactive terminal) — unlike `declined`, nothing is deleted and nothing is
   * committed: the fork stays registered (hidden, as any capture fork would be) and the written
   * files stay on disk, uncommitted, for a later interactive run to resolve (docs/QUESTOES.md
   * Q-091 — the spec is silent on this exact case; deleting real, approved-by-nobody-yet work
   * because a terminal wasn't attached would be worse than leaving it alone). */
  | {
      readonly kind: 'confirmationUnavailable';
      readonly projectId: string;
      readonly forkSessionId: string;
      readonly changedFiles: readonly string[];
      readonly manifestRestore: ManifestRestoreOutcome;
    }
  | {
      readonly kind: 'adopted';
      readonly projectId: string;
      readonly forkSessionId: string;
      /** V2-T73 item 2: what `restoreProjectManifestIfChanged` found and did to `seeya.json`,
       * computed right after the fork's own harness closed — BEFORE this call ever read what
       * changed, so a manifest the fork left dirty (item 1 guarantees it was never committed that
       * way) never shows up in `changedFiles`/`alreadyCommittedFiles` below. */
      readonly manifestRestore: ManifestRestoreOutcome;
      /** Files committed by THIS call's own `commitAdoption` — empty when there was nothing left
       * for seeya to commit itself (V2-T72 item 1: either the copy left nothing pending, or what
       * it left pending stayed uncommitted, see `pendingFiles` below). */
      readonly changedFiles: readonly string[];
      /** V2-T72 item 1: files the copy ITSELF already committed, while it still held the project
       * lock, before this call ever asked anything — found via `WorkspaceRepository
       * .findSessionCommits(root, projectId, forkSessionId)`, the same `Seeya-Session-Id` trailer
       * D-047 item 4 already requires every commit to carry (`core/workspace-commit-guard.ts`
       * writes it from the fork's own `CLAUDE_CODE_SESSION_ID`, which the fork's own
       * `--session-id ${forkSessionId}` sets). Empty in the ordinary case — a copy that never
       * committed on its own, the only case `adopted` used to mean before this task. **Where this
       * stops:** it only sees commits that went through the workspace's own git hook and got the
       * trailer; a commit made with `--no-verify` (D-047's own "não cobre o contorno
       * deliberado") would leave nothing here to find. */
      readonly alreadyCommittedFiles: readonly string[];
      /** V2-T72 item 1: files still sitting uncommitted after this adoption — the person declined
       * the follow-up question, there was no terminal to ask it through, or seeya's own attempt to
       * commit them failed (`pendingCommitFailedReason` says why, in that last case). Always empty
       * when nothing was left pending. Unlike the pre-fix behavior, the adoption is registered
       * regardless of what happens here: once the copy has left a real commit behind, it is never
       * discarded just because something else, afterward, didn't get committed too. */
      readonly pendingFiles: readonly string[];
      /** Set only when `pendingFiles` is non-empty BECAUSE seeya tried and failed to commit them
       * (as opposed to the person declining, or no terminal being available to ask) —
       * `commitAll`'s own thrown message, same text `commitFailed` below already surfaces for the
       * ordinary (no prior commits) case. */
      readonly pendingCommitFailedReason?: string;
    }
  /** V2-T34 production defect (PO review, 2026-09-25): `commitAll` rejected — most often the
   * workspace's own commit-msg hook refusing the commit (`core/workspace-commit-guard.ts`), but
   * any git failure lands here. Same non-destructive handling as `confirmationUnavailable`: the
   * fork's files stay on disk uncommitted, `forks.json` keeps it registered as pending (a later
   * `seeya project adopt` on the SAME original session would still see `alreadyAdopted` is false
   * — nothing here marks the original as adopted), and `adoptions.json` never gets an entry.
   * `reason` is `commitAll`'s own thrown message, which now includes git's stderr
   * (`adapters/workspace/index.ts#commitAll`'s own fix, same PO review) — the caller (CLI/window)
   * shows it instead of the operation silently vanishing. */
  | {
      readonly kind: 'commitFailed';
      readonly projectId: string;
      readonly forkSessionId: string;
      readonly changedFiles: readonly string[];
      readonly reason: string;
      readonly manifestRestore: ManifestRestoreOutcome;
    };
