/**
 * The Claude Code project settings (D-047 item 5, V2-T34 item 2) that refuse the two ways a Bash
 * tool call could bypass the workspace's own git hooks (`core/workspace-commit-guard.ts`):
 * `git commit --no-verify`, and changing where git looks for hooks (`git config core.hooksPath`).
 * Written into a project's own `.claude/settings.json` (project configuration, D-030: never
 * `~/.claude/`) at project creation time only (`core/project-skeleton.ts#buildProjectSkeleton`) —
 * tracked, versioned content, like `AGENTS.md`/`INDEX.md`, not reinstalled on every `open` the way
 * the git hook itself is (`core/workspace-hooks.ts`'s own docstring on why THAT one has to live
 * outside git's tracked content instead).
 *
 * **Measured limit, not assumed (item 2's own "medir primeiro"): this layer does NOT protect
 * `seeya project adopt`.** Claude Code only reads a directory's own `.claude/settings.json` from
 * the session's `cwd`; a directory released only via `--add-dir` is never scanned for its own
 * settings/hooks (`https://code.claude.com/docs/en/permissions.md`: "doesn't discover most
 * `.claude/` configuration from these directories" — confirmed against the shipped documentation,
 * not inferred). `seeya project open` launches WITH the project directory as `cwd`
 * (`application/project-open.ts#openProject`), so this hook is active there. `seeya project adopt`
 * resumes a fork in the ORIGINAL session's own directory and only releases the project via
 * `--add-dir` (`core/ports.ts#SessionAdoptionLauncher`'s own docstring on why, D-047) — this hook
 * never runs for that flow. The git hooks (`core/workspace-commit-guard.ts`) still do, since they
 * run inside the workspace's own repository regardless of which directory a session calls `git`
 * from — this is exactly item 7's own "onde o guarda-corpo termina," for this one layer.
 */

export const HARNESS_SETTINGS_RELATIVE_PATH = '.claude/settings.json';
export const HARNESS_HOOK_SCRIPT_RELATIVE_PATH = '.claude/hooks/verify-bash-command.mjs';

/**
 * `https://code.claude.com/docs/en/hooks.md`'s own shape: `PreToolUse` hooks, matched on the exact
 * tool name `"Bash"` (case-sensitive), one `command`-type hook running the script below. Claude
 * Code substitutes `${CLAUDE_PROJECT_DIR}` into the command text itself before ever handing it to a
 * shell (the same doc's own "path placeholder"), so this resolves correctly on every platform this
 * project supports, never dependent on which shell ran the command.
 */
export function buildHarnessSettingsJson(): string {
  const settings = {
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash',
          hooks: [
            {
              type: 'command',
              command: `node "\${CLAUDE_PROJECT_DIR}/${HARNESS_HOOK_SCRIPT_RELATIVE_PATH}"`,
            },
          ],
        },
      ],
    },
  };
  return JSON.stringify(settings, null, 2) + '\n';
}

/**
 * A plain Node script (never a POSIX shell script, unlike `core/workspace-hooks.ts`'s own git
 * hook): Claude Code's own hook command runner is not guaranteed to be the same shell git's hook
 * execution uses, so this avoids depending on either one specifically — `node` on `PATH` is already
 * a hard requirement for Claude Code itself to run at all.
 *
 * Reads the `PreToolUse` payload from stdin, checks `tool_input.command` for either forbidden
 * pattern, and — only on a hit — writes the `permissionDecision: "deny"` JSON the docs describe to
 * stdout and exits `2` (the one exit code that blocks the tool call). Anything else (unparseable
 * payload, a non-Bash/no-`command` call, a command that matches neither pattern) exits `0`: this
 * hook never has an opinion beyond the two things it's here to refuse.
 */
export function buildHarnessHookScript(): string {
  return [
    '#!/usr/bin/env node',
    '// Generated by seeya (D-047, V2-T34 item 2). Refuses a Bash command that would bypass the',
    '// workspace\'s own git hooks (core/workspace-commit-guard.ts): "--no-verify", or changing',
    '// where git looks for hooks ("core.hooksPath"). Reads the PreToolUse payload from stdin',
    '// (https://code.claude.com/docs/en/hooks.md): { tool_name, tool_input: { command } }.',
    '//',
    "// KNOWN LIMIT (measured, not assumed): Claude Code only reads a directory's own",
    "// .claude/settings.json from the session's cwd, never from a directory released only via",
    '// --add-dir (https://code.claude.com/docs/en/permissions.md). "seeya project open" launches',
    '// WITH the project as cwd, so this hook is active there. "seeya project adopt" resumes a fork',
    "// in the ORIGINAL session's own directory and only releases the project via --add-dir — this",
    "// hook does not protect that path. The workspace's own git hooks still do.",
    '',
    'let raw = "";',
    'process.stdin.on("data", (chunk) => {',
    '  raw += chunk;',
    '});',
    'process.stdin.on("end", () => {',
    '  let payload;',
    '  try {',
    '    payload = JSON.parse(raw);',
    '  } catch {',
    "    process.exit(0); // Not our JSON to judge — never block on a payload we can't parse.",
    '  }',
    '  const command = payload && payload.tool_input && payload.tool_input.command;',
    '  if (typeof command !== "string") {',
    '    process.exit(0);',
    '  }',
    '  const forbidden = [/--no-verify\\b/, /hooksPath/i];',
    '  if (!forbidden.some((pattern) => pattern.test(command))) {',
    '    process.exit(0);',
    '  }',
    '  process.stdout.write(',
    '    JSON.stringify({',
    '      hookSpecificOutput: {',
    '        hookEventName: "PreToolUse",',
    '        permissionDecision: "deny",',
    '        permissionDecisionReason:',
    '          "This project\'s git hooks (D-047) enforce commit trailers and one-project-per-commit." +',
    '          " This command would bypass them. Ask the person running this session before working" +',
    '          " around it.",',
    '      },',
    '    }),',
    '  );',
    '  process.exit(2);',
    '});',
    '',
  ].join('\n');
}
