/**
 * The text of the workspace's own `commit-msg` git hook (D-047 item 5, V2-T34 item 1) — a small
 * POSIX shell script that hands the commit message file straight to `seeya project verify-commit`,
 * by ABSOLUTE path to both the Node binary and this project's own CLI entry point. Never relies on
 * `PATH`: a hook's own environment (set by whatever spawned `git commit` — a shell, an editor, a
 * harness's own tool call) can't be trusted to carry it, and the task's own instruction is explicit
 * ("não dependem de o seeya estar no PATH... chamam a verificação do próprio seeya pelo caminho
 * absoluto gravado ao instalar").
 *
 * **One script, every platform.** Git for Windows always runs its own hooks through the POSIX shell
 * it bundles (`sh.exe`), never `cmd.exe` — measured directly for this task (see the application
 * layer's own module comment for how) — so there is no second `.cmd`/PowerShell variant to
 * maintain.
 *
 * Pure: builds text only, never touches a filesystem — `application/workspace-hooks.ts` is what
 * actually writes this into `<root>/.git/hooks/commit-msg` and marks it executable.
 */

export const COMMIT_MSG_HOOK_FILE_NAME = 'commit-msg';

/**
 * `env` (V2-T30's own app composition): the interface (`packages/app/src`) points `nodePath` at
 * Electron's own binary, which only behaves as plain Node with `ELECTRON_RUN_AS_NODE=1` in its
 * environment (the same mechanism `packages/app/src/composition/index.ts#daemonLaunchTarget`
 * already relies on for its own detached daemon spawn) — inline `KEY=value` assignments before
 * `exec` is `sh`'s own portable way to set that for one command without a second script. Empty for
 * every CLI-launched hook (`packages/cli/src/composition.ts` never passes one), so the script stays
 * exactly the same one line shorter text it always was there.
 *
 * @example
 * buildCommitMsgHookScript('/usr/bin/node', '/opt/seeya/dist/index.js')
 * // '#!/bin/sh\n# Generated by seeya ...\nexec "/usr/bin/node" "/opt/seeya/dist/index.js" ' +
 * //   'project verify-commit "$1"\n'
 */
export function buildCommitMsgHookScript(
  nodePath: string,
  cliEntryPath: string,
  env: Readonly<Record<string, string>> = {},
): string {
  const envPrefix = Object.entries(env)
    .map(([key, value]) => `${key}=${value} `)
    .join('');
  return (
    '#!/bin/sh\n' +
    '# Generated by seeya (D-047). Verifies and completes the Seeya-Project-Id/Seeya-Session-Id\n' +
    '# commit trailers, and refuses commits that break project isolation (one project per commit,\n' +
    '# never the project lock, never a commit into a project locked by another live session).\n' +
    '# Reinstalled by every "seeya project open" — edits here are overwritten, not preserved.\n' +
    `${envPrefix}exec "${nodePath}" "${cliEntryPath}" project verify-commit "$1"\n`
  );
}
