/**
 * The text of the workspace's own `commit-msg` git hook (D-047 item 5, V2-T34 item 1) — a small
 * POSIX shell script that hands the commit message file straight to `seeya project verify-commit`,
 * by ABSOLUTE path to both the Node binary and this project's own CLI entry point. Never relies on
 * `PATH`: a hook's own environment (set by whatever spawned `git commit` — a shell, an editor, a
 * harness's own tool call) can't be trusted to carry it, and the task's own instruction is explicit
 * ("não dependem de o seeya estar no PATH... chamam a verificação do próprio seeya pelo caminho
 * absoluto gravado ao instalar").
 *
 * **One script, every platform.** Git for Windows always runs its own hooks through the POSIX shell
 * it bundles (`sh.exe`), never `cmd.exe` — measured directly for this task (see the application
 * layer's own module comment for how) — so there is no second `.cmd`/PowerShell variant to
 * maintain.
 *
 * Pure: builds text only, never touches a filesystem — `application/workspace-hooks.ts` is what
 * actually writes this into `<root>/.git/hooks/commit-msg` and marks it executable.
 */

import { resolveHookVerifierCheckPath } from './hook-verifier-path.js';

export const COMMIT_MSG_HOOK_FILE_NAME = 'commit-msg';

/**
 * `env` — `nodePath` may itself be Electron's own binary (either composition root, `cli/` or
 * `app/`, when THIS running `seeya` is packaged as the Electron app: `bin/seeya.cmd` on Windows,
 * `/usr/bin/seeya` on Linux, both launching the app's own executable), which only behaves as plain
 * Node with `ELECTRON_RUN_AS_NODE=1` in its environment (the same mechanism
 * `packages/app/src/composition/index.ts#daemonLaunchTarget` already relies on for its own
 * detached daemon spawn). Inline `KEY=value` assignments before `exec` is `sh`'s own portable way
 * to set that for one command without a second script — confirmed for real against Claude Code's
 * own hook command execution too (`core/harness-hook-config.ts`'s own docstring), so the same
 * technique is trusted here.
 *
 * **PO review (V2-T34, item 2): checks `nodePath`/`cliEntryPath` exist before calling them.** The
 * absolute path recorded here is only as fresh as the last `seeya project open` — if `seeya` moved
 * or was uninstalled since, the original version of this script just handed a nonexistent path to
 * `exec` and `sh` printed its own raw error, refusing the commit for a reason nobody reading it
 * could act on. The guard still fails closed (a missing verifier still refuses the commit,
 * `exit 1`) — what changed is that the refusal now names the exact path that's missing and how to
 * fix it. Real execution proof (not just simulated):
 * `tests/integration/workspace/commit-msg-hook.test.ts`'s own "missing verifier" scenario, a real
 * `git commit` against a hook installed with a nonexistent `nodePath`.
 *
 * @example
 * buildCommitMsgHookScript('/usr/bin/node', '/opt/seeya/dist/index.js')
 * // '#!/bin/sh\n# Generated by seeya ...\nif [ -f "/usr/bin/node" ] && ' +
 * //   '[ -f "/opt/seeya/dist/index.js" ]; then exec "/usr/bin/node" "/opt/seeya/dist/index.js" ' +
 * //   'project verify-commit "$1"; else echo "seeya: ..." >&2; exit 1; fi\n'
 */
export function buildCommitMsgHookScript(
  nodePath: string,
  cliEntryPath: string,
  env: Readonly<Record<string, string>> = {},
): string {
  const envPrefix = Object.entries(env)
    .map(([key, value]) => `${key}=${value} `)
    .join('');
  // No literal double quotes inside this text (AGENTS.md's own reasoning made explicit here, not
  // just a style choice): the whole message is wrapped in a double-quoted `echo` below, and a `"`
  // in the middle of it would end that string early, mid-shell-script, taking whatever came after
  // as a separate (malformed) command — 'seeya project open <id>' uses single quotes for exactly
  // that reason.
  const missingVerifierMessage =
    `seeya: the workspace's own commit-msg hook can't find its seeya binary (looked for ` +
    `${nodePath} and ${cliEntryPath}). Run 'seeya project open <id>' to reinstall the hooks.`;
  // PO review production defect (2026-09-25): a packaged `cliEntryPath` lives inside `app.asar` —
  // `[ -f ... ]` on the full inner path always fails (`core/hook-verifier-path.ts`'s own
  // docstring), so the pre-flight checks the `.asar` file itself instead. The `exec` line below
  // still gets the REAL `cliEntryPath` — Electron's own patched `fs` needs the full inner path to
  // actually load the module.
  const cliEntryCheckPath = resolveHookVerifierCheckPath(cliEntryPath);
  return (
    '#!/bin/sh\n' +
    '# Generated by seeya (D-047). Verifies and completes the Seeya-Project-Id/Seeya-Session-Id\n' +
    '# commit trailers, and refuses commits that break project isolation (one project per commit,\n' +
    '# never the project lock, never a commit into a project locked by another live session).\n' +
    '# Reinstalled by every "seeya project open" — edits here are overwritten, not preserved.\n' +
    `if [ -f "${nodePath}" ] && [ -f "${cliEntryCheckPath}" ]; then ` +
    `${envPrefix}exec "${nodePath}" "${cliEntryPath}" project verify-commit "$1"; ` +
    `else echo "${missingVerifierMessage}" >&2; exit 1; fi\n`
  );
}
