/**
 * zod schema for the output of `claude -p --output-format json` — what `adapters/generation`
 * uses to get the understanding generated by the model (D-003, D-011). See docs/ARQUITETURA.md
 * § generation/.
 *
 * **Important difference from this task's (S0-T5) other three schemas.** The schemas in
 * `discovery/schemas.ts` and `transcript/schemas.ts` were confirmed line by line against real
 * files and commands on this machine (`tests/contract/`). This one **could not be confirmed the
 * same way**: `docs/PLANO-DE-ENTREGA.md` and `CLAUDE.md` forbid any test that touches the
 * network, and producing this output requires a real API call. The shape below is what the PO
 * gathered on this machine and handed over as task input — it's treated as the best evidence
 * available, not as a guess. It follows the same principle as the other two (strict on the
 * fields the spec says are used, tolerant of the rest), but the first time this schema runs
 * against real output for real is a natural candidate for a new contract test — not for a
 * preemptive loosening.
 *
 * `type` and `subtype` stay free-form strings, not a literal: it's the documented output of
 * `claude -p`'s `--output-format json` mode (D-011, D-015), but without empirical confirmation
 * in this task that the values observed here exhaust the possible set.
 *
 * **Re-checked against `docs/spikes/A-resume-headless.md`** after fixing the misleading excerpt
 * the document carried (S0-T5 review): the real output has 20 top-level fields, and the 12
 * required below are all among them — no required field here is invented.
 * `api_error_status`, `duration_api_ms`, `fast_mode_state`, `stop_reason`, `terminal_reason`,
 * `time_to_request_ms`, `ttft_ms` and `ttft_stream_ms` also appear in the real output but are
 * left out of the schema for not having a defined use yet — dropped by the default `z.object()`,
 * not a problem.
 *
 * **`structured_output`, confirmed against a real local `claude -p` call (S2-T2, claude
 * 2.1.235), is exactly the "future contract test" this comment used to call for** — the first
 * time this schema ran against real output. `--json-schema` adds this field: the already-parsed
 * object, not just the JSON-stringified copy `result` also carries. `adapters/generation` reads
 * `structured_output` first and only falls back to `JSON.parse(result)` if it's missing — see
 * `understanding-schema.ts`. Declared `.optional()` here (not required) because a call made
 * without `--json-schema` — none in this codebase, but nothing in the schema itself should assume
 * that — legitimately won't have it (D-021 spirit: a field only one call shape produces isn't
 * "corruption" in the other shape).
 */
import { z } from 'zod';

const usageSchema = z.object({
  input_tokens: z.number().int().nonnegative(),
  output_tokens: z.number().int().nonnegative(),
  cache_creation_input_tokens: z.number().int().nonnegative(),
  cache_read_input_tokens: z.number().int().nonnegative(),
});

export const claudePrintOutputSchema = z.object({
  type: z.string().min(1),
  subtype: z.string().min(1),
  is_error: z.boolean(),
  duration_ms: z.number().nonnegative(),
  num_turns: z.number().int().nonnegative(),
  result: z.string(),
  session_id: z.uuid(),
  total_cost_usd: z.number().nonnegative(),
  usage: usageSchema,
  // Not detailed: the spec doesn't define yet what `seeya` extracts from them (D-003 only talks
  // about "understanding"). They stay as a minimal tolerant structure until a future task needs
  // a specific field — at that point they get their own shape, not `z.unknown()` forever.
  modelUsage: z.record(z.string(), z.unknown()),
  permission_denials: z.array(z.unknown()),
  uuid: z.uuid(),
  structured_output: z.unknown().optional(),
});

export type ClaudePrintOutput = z.infer<typeof claudePrintOutputSchema>;
